on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: autorelease

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Whole history is needed for Sonar scan

      # release-please
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: master
          package-name: app1
          component: app1
          release-type: simple

