on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

name: autorelease

jobs:
  release-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v3
        with: {node-version: 18, cache: npm}
      - run: npm ci
      - run: npx nx run-many --target=release --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
