on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: autorelease

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # release-please
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
