on:
  workflow_dispatch:
    inputs:
      app:
        description: 'select app'
        required: true
        type: choice
        options:
          - 'app1'
          - 'app2'


permissions:
  contents: write
  pull-requests: write

name: release app

jobs:
  release-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_SSH_KEY }}
          ssh-known-hosts: 'github.com'
      - uses: actions/setup-node@v3
        with: {node-version: 18, cache: npm}
      - run: npm install --force
      - id: resolveCoveragePaths
        run: |
          echo ${{ secrets.RELEASE_SSH_KEY }} > /tmp/git_deploy_key
          ssh-add /tmp/git_deploy_key
          npx nx run ${{ github.event.inputs.app }}:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
