on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

name: release app2

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v3
        with: {node-version: 18, cache: npm}
      - run: npm ci
      - run: npx nx run app2:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
